Fix issue where match is null
Apparently, match can be null, which caused the following error. Checking for nullness fixes the problem

`
C:\Users\sd\Documents\ExcelTemplating\node_modules\xlsx-template\lib\index.js:544
            table: match[1] || null,
                        ^

TypeError: Cannot read property '1' of null
    at Workbook.module.exports.Workbook.splitRef (C:\Users\sd\Documents\ExcelTemplating\node_modules\xlsx-template\lib\index.js:544:25)
    at C:\Users\sd\Documents\ExcelTemplating\node_modules\xlsx-template\lib\index.js:1000:37
    at Array.forEach (native)
    at Workbook.module.exports.Workbook.pushDown (C:\Users\sd\Documents\ExcelTemplating\node_modules\xlsx-template\lib\index.js:981:54)
    at C:\Users\sd\Documents\ExcelTemplating\node_modules\xlsx-template\lib\index.js:231:22
    at Array.forEach (native)
    at Workbook.module.exports.Workbook.substitute (C:\Users\sd\Documents\ExcelTemplating\node_modules\xlsx-template\lib\index.js:133:34)
    at C:\Users\sd\Documents\ExcelTemplating\excelTemplating2.js:25:11
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
`